						CONSTRAINTS AND FUNCTIONS


--To assign a primary key to the BANK_CUST table


	ALTER TABLE BANK_CUST ADD CONSTRAINT PK_CUST_ID
	PRIMARY KEY (CUST_ID);

--To assign a foreign key to the BANK_CUST_CONTACT table 
	
	ALTER TABLE BANK_CUST_CONTACT ADD CONSTRAINT FK_CUST_ID
	FOREIGN KEY (CUST_ID) REFERENCES BANK_CUST (CUST_ID)
	ON DELETE CASCADE;

--To assign a primary key to the BANK_EMPLOYEE table
	
	ALTER TABLE BANK_EMPLOYEE ADD CONSTRAINT PK_BANK_EMP_ID 
	PRIMARY KEY (BANK_EMP_ID);


-- WRITE A FUNCTION TO COUNT THE NUMBER OF CUSTOMERS AND SHOULD RETURN THE COUNT

	CREATE OR REPLACE FUNCTION COUNT_BANK_CUST RETURN NUMBER
	IS
	V_CUST_COUNT NUMBER;
	BEGIN
	SELECT COUNT(*) INTO V_CUST_COUNT FROM BANK_CUST;
 	RETURN V_CUST_COUNT;
	EXCEPTION
 	WHEN OTHERS THEN
 	RETURN NULL;
	END COUNT_BANK_CUST;
--SELECT COUNT_BANK_CUST FROM DUAL;



-- WRITE A PROCEDURE TO ADD A CUSTOMER TO THE BANK_CUST TABLE
-- 1. THE CUST_ID SHOULD BE AUTO-GENERATED
-- 2. THE CUSTOMER FIRST,LAST AND INITIAL SHOULD BE IN INITCAP
-- 3. THE GENDER SHOULD BE M OR F
-- 4. THE CUSTOMER TYPE SHOULD BE IND OR CORP
-- 5. THE DEFAULT GENDER SHOULD BE F
-- 6. THE DEFAULT CUST TYPE SHOULD BE IND

	CREATE OR REPLACE PROCEDURE PR_ADD_CUSTOMER 
	(P_CUST_FIRST_NAME BANK_CUST.CUST_FIRST_NAME%TYPE,
	 P_INITIALS BANK_CUST.INITIALS%TYPE,
 	P_CUST_LAST_NAME BANK_CUST.CUST_LAST_NAME%TYPE,
 	P_CUST_GENDER BANK_CUST.CUST_GENDER%TYPE DEFAULT 'F',
 	P_CUST_DOB BANK_CUST.CUST_DOB%TYPE,
 	P_CUST_TYPE BANK_CUST.CUST_TYPE%TYPE DEFAULT 'IND')
	IS
	V_COUNT NUMBER;
	V_CUST_ID BANK_CUST.CUST_ID%TYPE;
	ESTOP EXCEPTION;
	BEGIN
        IF UPPER(P_CUST_GENDER) NOT IN ('M','F') THEN
        RAISE ESTOP;
        END IF;
        IF UPPER(P_CUST_TYPE) NOT IN ('IND','CORP') THEN
        RAISE ESTOP;
       END IF;
       V_COUNT:=COUNT_BANK_CUST;
       IF V_COUNT=0 THEN
      V_CUST_ID:=4101;
       ELSE
        SELECT MAX(CUST_ID)+1 INTO V_CUST_ID FROM BANK_CUST;
      END IF;

EXCEPTION
   WHEN ESTOP THEN
    RAISE_APPLICATION_ERROR (-20001,'THE GENDER OR CUSTOMER TYPE HAS BEEN INCORRECTLY SPECIFIED');
   WHEN OTHERS THEN
    NULL;
END PR_ADD_CUSTOMER;



-- WRITE A FUNCTION TO ACCEPT A CUST_ID AND RETURN 1 IF 
-- CUSTOMER IS EXISTING AND -1 IF CUSTOMER IS NOT EXISTING


CREATE OR REPLACE FUNCTION CHECK_CUST_ID (P_CUST_ID IN BANK_CUST.CUST_ID%TYPE)
RETURN NUMBER IS
  CURSOR C1(P_CUR_CUST_ID IN BANK_CUST.CUST_ID%TYPE) 
  IS 
  SELECT 'A' FROM BANK_CUST 
  WHERE CUST_ID=P_CUR_CUST_ID;
  V_TEMP CHAR(1);
BEGIN
  OPEN C1(P_CUST_ID);
  FETCH C1 INTO V_TEMP;
  CLOSE C1;
  IF V_TEMP='A' THEN
    RETURN 1;
  ELSE
    RETURN -1;
  END IF;
INSERT INTO BANK_CUST 
  VALUES
  (V_CUST_ID,
   INITCAP(P_CUST_FIRST_NAME),
   INITCAP (P_INITIALS),
   INITCAP(P_CUST_LAST_NAME) ,
   UPPER(P_CUST_GENDER) ,
   P_CUST_DOB ,
   UPPER(P_CUST_TYPE) );
EXCEPTION 
  WHEN OTHERS THEN
    RETURN NULL;
END CHECK_CUST_ID;


-- WRITE A PROCEDURE TO ADD A BANK CUSTOMER CONTACT
-- 1. THE CUST_ID SHOULD EXIST IN THE BANK_CUST TABLE
-- 2. THE CUST_PHONE SHOULD BE MAX 10 DIGITS MIN 6 DIGITS
-- 3. THE CONTACT TYPE SHOULD BE HOME OR OFFICE
-- 4. CUST_ADDR_LINE1,CUST_ADDR_LINE2,CUST_CITY,CUST_STATE
--    SHOULD BE IN INITCAP
-- 5. CUST_PIN SHOULD NOT EXCEED 6 DIGITS
-- 6. THE CUSTOMER CONTACT TYPE DEFAULT SHOULD BE HOME


CREATE OR REPLACE PROCEDURE PR_ADD_CUST_CONTACT
(P_CUST_ID  BANK_CUST_CONTACT.CUST_ID%TYPE,
 P_CUST_PHONE BANK_CUST_CONTACT.CUST_PHONE%TYPE,
 P_CONTACT_TYPE BANK_CUST_CONTACT.CONTACT_TYPE%TYPE DEFAULT 'HOME',
 P_CUST_ADDR_LINE1 BANK_CUST_CONTACT.CUST_ADDR_LINE1%TYPE,
 P_CUST_ADDR_LINE2 BANK_CUST_CONTACT.CUST_ADDR_LINE2%TYPE,
 P_CUST_CITY BANK_CUST_CONTACT.CUST_CITY%TYPE,
 P_CUST_STATE BANK_CUST_CONTACT.CUST_STATE%TYPE,
 P_CUST_PIN BANK_CUST_CONTACT.CUST_PIN%TYPE) IS
V_TEMP NUMBER;
ESTOP1  EXCEPTION;
ESTOP2  EXCEPTION;
ESTOP3  EXCEPTION;
ESTOP4  EXCEPTION;
BEGIN
 V_TEMP:=CHECK_CUST_ID(P_CUST_ID);
 IF V_TEMP=-1 THEN
  RAISE ESTOP1;
 END IF;
 IF LENGTH(P_CUST_PHONE) NOT BETWEEN 6 AND 10 THEN
  RAISE ESTOP2;
 END IF;
 IF P_CONTACT_TYPE NOT IN ('HOME','OFFICE') THEN
  RAISE ESTOP3;
 END IF; 
 IF LENGTH(P_CUST_PIN)<>6 THEN
  RAISE ESTOP4;
 END IF; 
INSERT INTO BANK_CUST_CONTACT
 VALUES
 (P_CUST_ID  ,
 P_CUST_PHONE ,
 P_CONTACT_TYPE ,
 INITCAP(P_CUST_ADDR_LINE1) ,
 INITCAP(P_CUST_ADDR_LINE2) ,
 INITCAP(P_CUST_CITY) ,
 INITCAP(P_CUST_STATE) ,
 P_CUST_PIN );
 COMMIT;
 EXCEPTION
 WHEN ESTOP1 THEN
 RAISE_APPLICATION_ERROR(-20002,'THE CUSTOMER ID IS NOT CORRECT');
 WHEN ESTOP2 THEN
 RAISE_APPLICATION_ERROR(-20003,'THE CUSTOMER PHONE IS NOT CORRECT NO OF DIGITS');
 WHEN ESTOP3 THEN
 RAISE_APPLICATION_ERROR(-20004,'THE CUSTOMER CONTACT TYPE IS NOT CORRECT');
 WHEN ESTOP4 THEN
 RAISE_APPLICATION_ERROR(-20005,'THE CUSTOMER CONTACT PIN IS NOT CORRECT');
 WHEN OTHERS THEN
  NULL;
END PR_ADD_CUST_CONTACT;










